### PR TITLE
More robust Git commands

### PR DESCRIPTION
**Pull request by borpin**
I do not think the git commands are robust enough and they can be run every time.

You can end up appearing to be on stable when you are not.

### CODE REVIEW

**Comment by borpin** [comment]
Bit more detail;

A fresh pull of emonhub gives me this/
```
pi@emonpi:~/test/emonhub $ git branch -vv
  master e45d602 [origin/master] check for conf/nodes directory
* stable 62446cb [origin/stable] Merge branch 'stable' of https://github.com/openenergymonitor/emonhub into stable
```

My emonhub directory looked like this.

```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
* (HEAD detached at origin/stable) 62446cb Merge branch 'stable' of https://github.com/openenergymonitor/emonhub into stable
  emon-pi                          6975b0d [origin/emon-pi: ahead 20, behind 13] Use a beta version number.
  stable                           e443b94 [origin/emon-pi] Merge pull request #95 from borpin/patch-3
```
note both the local branches are tracking the remote `origin/emon-pi` so `stable` is a clone of  `origin/emon-pi` instead of `origin/stable` as intended.

It has taken me a while but
```
git fetch --all --prune -v
git branch --set-upstream-to=origin/stable stable
git checkout origin/stable
git pull origin stable
```

Now I see
```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
* (HEAD detached at origin/stable) 62446cb Merge branch 'stable' of https://github.com/openenergymonitor/emonhub into stable
  emon-pi                          6975b0d [origin/emon-pi: ahead 20, behind 13] Use a beta version number.
  stable                           e443b94 [origin/stable: behind 29] Merge pull request #95 from borpin/patch-3
```

But I cannot get a pull to do what I want!

**Comment by borpin** [comment]
More still

Starting here

```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
* (HEAD detached from origin/stable) e45d602 check for conf/nodes directory
  emon-pi                            6975b0d [origin/emon-pi: ahead 20, behind 13] Use a beta version number.
  stable                             e443b94 [origin/stable: behind 29] Merge pull request #95 from borpin/patch-3
```
First delete the emon-pi branch

```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -D emon-pi
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
* (HEAD detached at origin/stable) 62446cb Merge branch 'stable' of https://github.com/openenergymonitor/emonhub into stable
  stable                           e443b94 [origin/stable: behind 29] Merge pull request #95 from borpin/patch-3
```

note stable still behind

I wonder if at this point I would be able to just do a `git pull stable` - never tried it.

what I did was
```
git checkout master
```

```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
* master e45d602 [origin/master] check for conf/nodes directory
  stable e443b94 [origin/stable: behind 29] Merge pull request #95 from borpin/patch-3
pi@emonpi:/opt/openenergymonitor/emonhub $ git checkout stable
Switched to branch 'stable'
Your branch is behind 'origin/stable' by 29 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
pi@emonpi:/opt/openenergymonitor/emonhub $ git pull
Updating e443b94..62446cb
Fast-forward

```

and finally
```
pi@emonpi:/opt/openenergymonitor/emonhub $ git branch -vv
  master e45d602 [origin/master] check for conf/nodes directory
* stable 62446cb [origin/stable] Merge branch 'stable' of https://github.com/openenergymonitor/emonhub into stable
```

Whew, gets me to where a fresh clone gives me!

**Comment by TrystanLea** [comment]
Thanks @borpin would it be possible to specify the branch in the config.ini file rather than:?

    git checkout origin/stable
    git pull origin stable

**Comment by borpin** [comment]
Ah, good question.

`$emonhub_branch` is available and used in the `install` script for emonhub.

Problem here is, does the config file get updated?  An old config will specify  `emon-pi`. What if someone manually switches branches?

I have found that on occasions, a simple git pull doesn't work. I'm also concerned that the local repo is tracking the wrong remote repo. I don't fully understand the implications of that.

**Comment by TrystanLea** [comment]
`Problem here is, does the config file get updated? An old config will specify emon-pi. What if someone manually switches branches?`

Yes true, pretty sure its not updated. 

Would the following interim change be one step forwards?

    branch=$(git rev-parse --abbrev-ref HEAD)
    if [ $branch == "emon-pi" ]; then
        git fetch --all --prune -v
        git checkout origin/stable
        git pull origin stable
        
        sudo apt-get update
        ./install.sh $emonSD_pi_env
    else
        git fetch --all --prune -v
        git branch
        git status
        git pull
    fi

**Comment by TrystanLea** [comment]
We can of course git pull the correct branch by using the detected branch.

Here's the latest implementation with a more verbose output as well (live in stable now)

    branch=$(git rev-parse --abbrev-ref HEAD)
    if [ $branch == "emon-pi" ]; then
        echo "Migrating from emon-pi branch to stable branch"
        echo
        echo "git fetch --all --prune -v"
        git fetch --all --prune -v
        echo "git checkout stable"
        git checkout stable
        echo "git pull origin stable"
        git pull origin stable
        echo
        echo "running emonhub install script emonSD_pi_env:$emonSD_pi_env"
        ./install.sh $emonSD_pi_env
    else
        echo "git fetch --all --prune -v"
        git fetch --all --prune -v
        echo "git status"
        git status
        echo "git pull origin $branch"
        git pull origin $branch
    fi

**Pull request closed without merging**
